# Generated by Django 4.0b1 on 2021-11-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0002_currencyconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='default_currency',
            field=models.BooleanField(default=False),
        ),
    ]
