# Generated by Django 4.0rc1 on 2021-11-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0011_transactionjournal_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
