# Generated by Django 4.0rc1 on 2021-11-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0013_account_accountstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountstring',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Account'),
        ),
    ]
