# Generated by Django 4.0rc1 on 2021-11-28 11:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('blackbook', '0014_alter_account_accountstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionjournal',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
