# Generated by Django 4.0rc1 on 2021-11-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0015_transactionjournal_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blackbook.transactionjournal'),
        ),
    ]
