# Generated by Django 4.0rc1 on 2021-12-02 22:36

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('blackbook', '0017_alter_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionjournal',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
