# Generated by Django 4.0 on 2021-12-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0018_alter_transactionjournal_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['amount', 'currency']},
        ),
    ]
