# Generated by Django 4.0 on 2021-12-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0020_budget_budgetperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_period',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('half_year', 'Every 6 months'), ('year', 'Year')], default='month', max_length=30),
        ),
    ]
