# Generated by Django 4.0 on 2021-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0021_userprofile_default_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='auto_budget',
            field=models.CharField(choices=[('no', 'No auto-budget'), ('add', 'Add left-over budget to new period'), ('fixed', 'Fixed budget for each period')], default='no', max_length=30),
        ),
        migrations.AddField(
            model_name='budget',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active?'),
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('half_year', 'Every 6 months'), ('year', 'Year')], default='month', max_length=30, null=True),
        ),
    ]
