# Generated by Django 4.0 on 2021-12-10 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0025_rename_budget_transactionjournal_budgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_currency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.currency'),
        ),
    ]
