# Generated by Django 4.0 on 2021-12-10 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0026_alter_userprofile_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionjournal',
            name='budgets',
            field=models.ManyToManyField(blank=True, to='blackbook.Budget'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.currency'),
        ),
    ]
