# Generated by Django 4.0b1 on 2021-11-13 10:13

from django.db import migrations


def create_default_currencies(apps, schema_editor):
    Currency = apps.get_model("blackbook", "Currency")

    Currency.objects.create(code="EUR", name="Euro")


class Migration(migrations.Migration):

    dependencies = [
        ("blackbook", "0003_currency_default_currency"),
    ]

    operations = [migrations.RunPython(create_default_currencies)]
