# Generated by Django 4.0rc1 on 2021-11-22 07:13

from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0007_alter_userprofile_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active?')),
                ('include_on_net_worth', models.BooleanField(default=True, help_text='Include this account when calculating the overall net worth?', verbose_name='include in net worth calculations?')),
                ('include_on_dashboard', models.BooleanField(default=True, help_text='Include this account on the dashboard?', verbose_name='include on dashboad?')),
                ('type', models.CharField(choices=[('assets', 'Assets'), ('income', 'Income'), ('expenses', 'Expenses'), ('liabilities', 'Liabilities'), ('cash', 'Cash'), ('equity', 'Equity')], max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('iban', localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, null=True, use_nordea_extensions=False, verbose_name='IBAN')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('currencies', models.ManyToManyField(blank=True, help_text='Optional, in case currencies are selected, the account will be restricted to accepting transactions only in this currency.', to='blackbook.Currency')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blackbook.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_account_name_for_parent'),
        ),
    ]
