# Generated by Django 4.0rc1 on 2021-11-23 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blackbook', '0010_alter_account_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('payee', models.CharField(blank=True, max_length=250, null=True)),
                ('short_description', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'created'],
                'get_latest_by': 'date',
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='uuid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blackbook.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blackbook.currency'),
        ),
        migrations.DeleteModel(
            name='TransactionLeg',
        ),
        migrations.AddField(
            model_name='transaction',
            name='journal_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_legs', to='blackbook.transactionjournal'),
            preserve_default=False,
        ),
    ]
